/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my_package;

import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author AILEEN
 */
public class search extends javax.swing.JFrame {

    public Connection con;
    public Statement stat;
    public ResultSet res;
    
    private String title;
    // Constructor
    public search(String searchQuery, String searchResults) {
        initComponents();

        // Check if the search results contain an error message
        if (searchResults.startsWith("No results found")) {
            // Display an error message
            JOptionPane.showMessageDialog(rootPane, searchResults, "", JOptionPane.ERROR_MESSAGE);
            
        } else {
            // Display search results in the text panes
            displaySearchResults(searchResults);
        }
    }
    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        java.awt.Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
        public String getTitle() {
        return title;  // Getter method for title
    }


    public void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/coba_perpustakaan", "root", "");
            stat = con.createStatement();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void displaySearchResults(String searchResults) {
        // Split the search results into individual lines
        String[] lines = searchResults.split("\n");

        // Assuming the format is "Title: ..., Author: ..., Category: ..., Quantity: ..."
        for (String line : lines) {
            if (line.startsWith("Title: ")) {
                jTextPane3.setText(line.substring("Title: ".length()).trim());
            } else if (line.startsWith("Author: ")) {
                jTextPane1.setText(line.substring("Author: ".length()).trim());
            } else if (line.startsWith("Category: ")) {
                jTextPane4.setText(line.substring("Category: ".length()).trim());
            } else if (line.startsWith("Quantity: ")) {
                jTextPane2.setText(line.substring("Quantity: ".length()).trim());
            }
        }
    }
    /**
     * Creates new form search
     */
//    public search(String searchQuery, String searchResults) {
//        initComponents();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(237, 202, 151));

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(237, 202, 151));
        jTextPane1.setBorder(null);
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 430, 30));

        jButton2.setBackground(new java.awt.Color(237, 202, 151));
        jButton2.setText("back");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        jButton3.setBackground(new java.awt.Color(237, 178, 115));
        jButton3.setText("OK");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 60, -1));

        jScrollPane2.setBackground(new java.awt.Color(237, 202, 151));

        jTextPane2.setEditable(false);
        jTextPane2.setBackground(new java.awt.Color(237, 202, 151));
        jTextPane2.setBorder(null);
        jScrollPane2.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 430, 30));

        jScrollPane3.setBackground(new java.awt.Color(237, 202, 151));

        jTextPane3.setEditable(false);
        jTextPane3.setBackground(new java.awt.Color(237, 202, 151));
        jTextPane3.setBorder(null);
        jScrollPane3.setViewportView(jTextPane3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 430, 30));

        jScrollPane4.setBackground(new java.awt.Color(237, 202, 151));

        jTextPane4.setEditable(false);
        jTextPane4.setBackground(new java.awt.Color(237, 202, 151));
        jTextPane4.setBorder(null);
        jScrollPane4.setViewportView(jTextPane4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 430, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component/SEARCH.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        close();
        home home  = new home();
        home.setVisible(rootPaneCheckingEnabled); // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        close();
        home home  = new home();
        home.setVisible(rootPaneCheckingEnabled); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     String searchQuery = "your_search_query"; // Provide an actual search query
    String searchResults = "your_search_results"; // Provide actual search results

    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new search(searchQuery, searchResults).setVisible(true);
        }
    });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    // End of variables declaration//GEN-END:variables
}
